"""Minimal asset catalogue port."""

from typing import Protocol
from uuid import UUID

from .domain import Asset, ExternalIdentifier, Instrument, Venue


class AssetRepository(Protocol):
    def save_asset(self, asset: Asset) -> None: ...
    def get_asset(self, asset_id: UUID) -> Asset: ...
    def list_assets(self) -> tuple[Asset, ...]: ...
    def save_venue(self, venue: Venue) -> None: ...
    def get_venue(self, venue_id: UUID) -> Venue: ...
    def save_instrument(self, instrument: Instrument) -> None: ...
    def get_instrument(self, instrument_id: UUID) -> Instrument: ...
    def list_instruments(self, asset_id: UUID) -> tuple[Instrument, ...]: ...
    def save_identifier(self, identifier: ExternalIdentifier) -> None: ...
    def list_identifiers(self, instrument_id: UUID) -> tuple[ExternalIdentifier, ...]: ...
